<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.7" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Private\MeUi.Authentication.Core.Infrastructure\MeUi.Authentication.Core.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Private\MeUi.Authentication.Core.Application\MeUi.Authentication.Core.Application.csproj" />
    <ProjectReference Include="..\..\Private\MeUi.Authentication.Core.Domain\MeUi.Authentication.Core.Domain.csproj" />
    <ProjectReference Include="..\..\Private\MeUi.Authentication.Core.Endpoint\MeUi.Authentication.Core.Endpoint.csproj" />
    <ProjectReference Include="..\MeUi.Authentication.Core.Shared\MeUi.Authentication.Core.Shared.Application\MeUi.Authentication.Core.Shared.Application.csproj" />
    <ProjectReference Include="..\MeUi.Authentication.Core.Shared\MeUi.Authentication.Core.Shared.Infrastructure\MeUi.Authentication.Core.Shared.Infrastructure.csproj" />
  </ItemGroup>

</Project>
