<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\MeUi.Shared\MeUi.Shared.ApplicationContract\MeUi.Shared.ApplicationContract.csproj" />
    <ProjectReference Include="..\..\..\MeUi.Authorization.Core\Public\MeUi.Authorization.Core.ApplicationContract\MeUi.Authorization.Core.ApplicationContract.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
