<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Private\MeUi.Authentication.Password.Infrastructure\MeUi.Authentication.Password.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Private\MeUi.Authentication.Password.Application\MeUi.Authentication.Password.Application.csproj" />
    <ProjectReference Include="..\..\Private\MeUi.Authentication.Password.Endpoints\MeUi.Authentication.Password.Endpoints.csproj" />
    <ProjectReference Include="..\..\Private\MeUi.Authentication.Password.Domain\MeUi.Authentication.Password.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
