<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MeUi.Authorization.Core.Domain\MeUi.Authorization.Core.Domain.csproj" />
    <ProjectReference Include="..\MeUi.Authorization.Core.Application\MeUi.Authorization.Core.Application.csproj" />
    <ProjectReference Include="..\..\..\..\MeUi.Shared\MeUi.Shared.Domain\MeUi.Shared.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\MeUi.Shared\MeUi.Shared.Application\MeUi.Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\..\MeUi.Shared\MeUi.Shared.Endpoint\MeUi.Shared.Endpoint.csproj" />
    <ProjectReference Include="..\..\Public\MeUi.Authorization.Core.ApplicationContract\MeUi.Authorization.Core.ApplicationContract.csproj" />
    <ProjectReference Include="..\..\Public\MeUi.Authorization.Core.Shared\MeUi.Authorization.Core.Shared.Endpoint\MeUi.Authorization.Core.Shared.Endpoint.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="7.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
