<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MeUi.Authentication.Password.Domain\MeUi.Authentication.Password.Domain.csproj" />
    <ProjectReference Include="..\MeUi.Authentication.Password.Application\MeUi.Authentication.Password.Application.csproj" />
    <ProjectReference Include="..\..\..\..\MeUi.Shared\MeUi.Shared.Infrastructure\MeUi.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\MeUi.Authentication.Core\Public\MeUi.Authentication.Core.Shared\MeUi.Authentication.Core.Shared.Infrastructure\MeUi.Authentication.Core.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
