<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MeUi.Authorization.Rbac.Application\MeUi.Authorization.Rbac.Application.csproj" />
    <ProjectReference Include="..\MeUi.Authorization.Rbac.Domain\MeUi.Authorization.Rbac.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\MeUi.Shared\MeUi.Shared.Infrastructure\MeUi.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\..\MeUi.Authentication\MeUi.Authentication.Password\Public\MeUi.Authentication.Password.ApplicationContract\MeUi.Authentication.Password.ApplicationContract.csproj" />
    <ProjectReference Include="..\..\..\..\MeUi.Authentication\MeUi.Authentication.Core\Public\MeUi.Authentication.Core.ApplicationContract\MeUi.Authentication.Core.ApplicationContract.csproj" />
    <ProjectReference Include="..\..\..\..\MeUi.Authentication\MeUi.Authentication.Core\Public\MeUi.Authentication.Core.Shared\MeUi.Authentication.Core.Shared.Application\MeUi.Authentication.Core.Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\..\MeUi.Authentication\MeUi.Authentication.Password\Public\MeUi.Authentication.Password.Shared\MeUi.Authentication.Password.Shared.Application\MeUi.Authentication.Password.Shared.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="7.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
