<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Public\MeUi.Authentication.Password.ApplicationContract\MeUi.Authentication.Password.ApplicationContract.csproj" />
    <ProjectReference Include="..\MeUi.Authentication.Password.Domain\MeUi.Authentication.Password.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\MeUi.Shared\MeUi.Shared.Application\MeUi.Shared.Application.csproj" />
    <ProjectReference Include="..\..\..\MeUi.Authentication.Core\Public\MeUi.Authentication.Core.ApplicationContract\MeUi.Authentication.Core.ApplicationContract.csproj" />
    <ProjectReference Include="..\..\..\MeUi.Authentication.Core\Public\MeUi.Authentication.Core.Shared\MeUi.Authentication.Core.Shared.Application\MeUi.Authentication.Core.Shared.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="7.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
