<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\MeUi.Shared\MeUi.Shared.Application\MeUi.Shared.Application.csproj" />
    <ProjectReference Include="..\..\Public\MeUi.Authorization.Rbac.ApplicationContract\MeUi.Authorization.Rbac.ApplicationContract.csproj" />
    <ProjectReference Include="..\MeUi.Authorization.Rbac.Domain\MeUi.Authorization.Rbac.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
