<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="9.2.0" />
    <PackageReference Include="FastEndpoints" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeUi.Shared.ApplicationContract\MeUi.Shared.ApplicationContract.csproj" />
    <ProjectReference Include="..\MeUi.Shared.Domain\MeUi.Shared.Domain.csproj" />
  </ItemGroup>

</Project>
